project:
  type: website
  output-dir: ../docs

website:
  title: "Digital Competence Dashboard"
  navbar:
    style: dark
    toggle: collapse
    left:
      - text: "{{< iconify ph book >}} Dimensions"
        menu:
          - href: strategic_information.qmd
            text: "{{< iconify ph target >}} Strategic Information"
          - href: critical_information.qmd
            text: "{{< iconify ph warning-circle >}} Critical Information"
          - href: netiquette.qmd
            text: "{{< iconify ph chat-circle-dots >}} Netiquette"
          - href: digital_content_creation.qmd
            text: "{{< iconify ph pen-nib >}} Digital Content Creation"
          - href: safety.qmd
            text: "{{< iconify ph shield-check >}} Safety"
          - href: digital_health.qmd
            text: "{{< iconify ph heart-pulse >}} Digital Health"
          - href: green_digital.qmd
            text: "{{< iconify ph leaf >}} Green Digital"
          - href: digital_problem_solving.qmd
            text: "{{< iconify ph toolbox >}} Digital Problem Solving"
          - href: transactional.qmd
            text: "{{< iconify ph credit-card >}} Transactional"
          - href: ai.qmd
            text: "{{< iconify ph brain >}} AI"
          - href: gen_ai.qmd
            text: "{{< iconify ph sparkle >}} Gen AI"
      - href: skills.qmd
        text: "{{< iconify ph chart-line >}} Skills"
      - href: performance.qmd
        text: "{{< iconify ph chart-line >}} Performance"
      - href: knowledge.qmd
        text: "{{< iconify ph chart-line >}} Knowledge"
      - href: highlights.qmd
        text: "{{< iconify ph target >}} Highlights"
    right:
      - href: about.qmd
        text: "{{< iconify ph info >}} About"
      - icon: github
        href: https://github.com/favstats/dashboardr
      - icon: twitter
        href: https://twitter.com/username
      - icon: linkedin
        href: https://linkedin.com/in/username
      - icon: envelope
        href: mailto:user@example.com
      - icon: globe
        href: https://example.com
    search: true
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: false
  page-footer: "Â© 2025 Digital Competences Dashboard - All Rights Reserved"

format:
  html:
    theme:
      - default
      - _tabset_minimal.scss

    math:
      engine: katex
    code-fold: true
    code-tools: true
    page-layout: full
    plausible:
      domain: "example.com"
